export const ReducersTypes = {
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  AUTH: "AUTH",
  DASHBOARD: "DASHBOARD",
  NAVIGATION: "NAVIGATION",
  NAVIGATION_RESET: "NAVIGATION_RESET",
  SETTINGS: "SETTINGS",
  SNACKBAR_DATA: "SNACKBAR_DATA",
  SNACKBAR_MSG: "SNACKBAR_MSG",
  SNACKBAR_RESET: "SNACKBAR_RESET",
  CONFIRMATION_BOX: "CONFIRMATION_BOX",
  CONFIRMATION_BOX_RESET: "CONFIRMATION_BOX_RESET",
  EMAIL_DATA: "EMAIL_DATA",
  EMAIL_RESET: "EMAIL_RESET",
  DYNAMIC_FORM: "DYNAMIC_FORM",
  ADD_DYNAMIC_FORM: "ADD_DYNAMIC_FORM",
  PREVIEW_DOCUMENT: "PREVIEW_DOCUMENT",
  RESET_PREVIEW_DOCUMENT: "RESET_PREVIEW_DOCUMENT",
  //UX
  INIT_UX: "INIT_UX",
  SET_UX: "SET_UX",
  RESET_UX: "RESET_UX",
  //User
  USER: "USER"
};
